### ISSUE TITLE
MqttClient thows exception

### ISSUE THREAD

**Issue by Schwenkner** [gnatmq/gnatmq#16]
I'm at the very beginning mit MQTT.

In a very simple excample I use mosquitto to play with mqtt on my raspberry.
When I do connect using the MqttClient from M2Mqtt library all works well. But I also would try to deploy the broker and since there is also a MqttClient in the GantMQ library, I'm executing the same code. When I do cliet.Connect("clientId") there are 4 exceptions thown "uPLibrary.Networking.M2Mqtt.Exceptions.MqttClientException" in GnatMQ.WinRT.dll" 

I didn't have the time yet to download the source code and debug more deep into. The first question I have, since there are no samples how to use the broker, can I use the client in this library the same way as in the M2Mqtt? Or is this a real bug?

**Comment by nkostis** [comment]
you cannot use the MqttClient class inside GnatMQ as an mqtt client. Although it's the same code, it's been compiled with the BROKER directive set, and is used by the broker to track clients.
You need to use Paolo's [M2MQTT](https://github.com/ppatierno/m2mqtt) dll for mqtt client operation.

Also, you cannot use both MqttClient classes in the same solution since they have the same namespace. There are workarounds for this, one is to take the [M2MQTT ](https://github.com/ppatierno/m2mqtt) project, change the namespace, compile it into a new .dll and reference it in your final solution

**Comment by dtflx01** [comment]
I'm using both GnatMQ as Broker and M2Mqtt as client in the same solution.
I'd to change the namespace in all files to avoid names conflicts in the GnatMQ solution.
