### ISSUE TITLE
Relation with gNatt

### ISSUE THREAD

**Issue by naboukho** [gnatmq/gnatmq#28]
I found this project https://github.com/jklemmack/gNatt and a lot of the code seems similar to GnatMQ. The problem is that the two projects have really different licenses so I need to know if the other project infringes on GnatMQ copyright and can't be used.

Thanks.

**Comment by ppatierno** [comment]
Hi,
thanks for providing me this information. There is absolutely no relation with my GnatMQ and this person other than copy the source code has removed the license header from files with my name and changed the license itself. I'll dig into it ... it's not the way of using source code from open projects.

Thanks !
Paolo

**Comment by naboukho** [comment]
Ok, good to know :)

Thanks for the info and you can close the issue as you solved my dilemma.

**Comment by jklemmack** [comment]
Being the owner of the gNatt repo, I have to chime in.  I'll concede that the original library was forked from another project, but I **did not** intentionally remove any copyright or license information.  It simply did not exist in the original source code in 2013, and you only added the EPL to this repo August of 2015.  

I know I downloaded the repo from *somewhere* and added it to GitHub so I had an off-premises store, but I can't seem to trace the specific history.  Eyeballing the code seems to indicate they had a common source.  I believe it had origins in M2Mqtt, but since that project on CodePlex has disappeared, I can't be certain.  It seems the other possible sources of truth - http://www.m2mqtt.net and https://github.com/ppatierno/m2mqtt - also no longer exist.

@ppatierno I'll add in the appropriate license or attribution if you'd like.  Or, given that I ended up mothballing it, I'm willing to delete my repo on GitHub.

**Comment by ppatierno** [comment]
@jklemmack no worries I see that you used M2Mqtt as reference right ? I see that you re-implemented the mqtt client. No problem for me.

The original M2Mqtt is now under the Eclipse Paho umbrella : https://github.com/eclipse/paho.mqtt.m2mqtt
And the web site is : https://m2mqtt.wordpress.com/

If you don't use the M2Mqtt code inside your repo please delete the directories.

Btw ... why a name so similar to mine ? :-) GnatMQ vs gNatt ?

**Comment by jklemmack** [comment]
I just went ahead & deleted it.  Fairest to all.

As for the name, it was a take on Mosquitto, and the propensity for adding "N" to .Net projects (NUnit, NServiceBus, NHibernate).  No similarity was intended.

**Comment by VladimirAkopyan** [comment]
I think this issue is closed now
